### ISSUE TITLE
[CraftQueue] Detected Job and levels are not in sync

### ISSUE THREAD

**Issue by ToxicMushroom** [Athavar/Athavar.FFXIV.Plugin#1]
I don't have a lvl 90 LTW and CUL, I do have a LVL 90 WVR so some seem to be swapped.
![image](https://user-images.githubusercontent.com/32853531/219875393-59659a25-275d-4015-ad46-8ab5596032a7.png)

I think that as a result of this issue the queue thinks I can't craft this item with the macro I inserted
![image](https://user-images.githubusercontent.com/32853531/219875492-dec96491-1088-4b71-b7cc-a9f191ab05fc.png)

**Comment by Athavar** [comment]
It looks like only the level is wrong detected, because the CP of  WVR is correct. I will have a look.

**Comment by Athavar** [comment]
I have fixed the problem with v2.0.13. Thanks for reporting this issue.
I have not encountered this problem, because all my Jobs are already on max level.

**Comment by ToxicMushroom** [comment]
The levels are in sync now yes but the gearset stats are still swapped.
![image](https://user-images.githubusercontent.com/32853531/222256617-cfac96a1-16c7-43a5-bede-fae53375b0c9.png)
Here is the gearset list with my ALC stats on the right.
You can prob see that it's swapped with the blacksmith. Others might be too.

**Comment by Athavar** [comment]
You have two gearsets for Alchemist. The stats are for gearset 12, but you have also a gearset for alchemist with id 6.
Note: Only the first gearset(with lower id) is used by [CraftQueue].

**Comment by ToxicMushroom** [comment]
> You have two gearsets for Alchemist. The stats are for gearset 12, but you have also a gearset for alchemist with id 6. Note: Only the first gearset(with lower id) is used by [CraftQueue].

I don't see duplicates here tho
![image](https://user-images.githubusercontent.com/32853531/222275318-97f99853-9ba0-4f6f-8e6d-049cb1253d0e.png)

**Comment by ToxicMushroom** [comment]
I do now see the duplicates in /ath yes, refreshing doens't help

**Comment by Athavar** [comment]
I found a solution: Each gearset has a "exists" flag.
With #3 non-existent gearsets will be filtered out.
