### ISSUE TITLE
[CraftQueue] Waste Not does not apply to Groundwork correctly

### ISSUE THREAD

**Issue by SpringEphemeral** [Athavar/Athavar.FFXIV.Plugin#16]
![2023-04-29 08 24 23](https://user-images.githubusercontent.com/43510864/235266620-bd55ae61-d52c-4b55-9896-a428a46768a1.png)

It appears that Groundwork's efficiency is being halved here as if it would cost 20 durability while the craft is currently at 10 durability, thus costing more than the craft's current durability. However, this is not the case as I'd still have a stack of Waste Not II active, making Groundwork cost 10 durability for this use, thus not costing more than the craft's current durability and giving it the full efficiency needed to complete the craft (3933/3696). 

This occurs when both Waste Not or Waste Not II is still active and Groundwork is used while the craft's durability is below 20, but still greater than, or equal to 10. I have also tested this macro with the same stats CraftQueue has recorded manually many times, and with Teamcraft for 100% reliability.

Thank you for your hard work though, this will definitely make precrafts much less of a chore.

**Comment by Athavar** [comment]
Fix is in release v2.0.21
