### ISSUE TITLE
Athavar.FFXIV.Plugin.Cheat isn't working anymore

### ISSUE THREAD

**Issue by kyrioA** [Athavar/Athavar.FFXIV.Plugin#33]
I don't really know anything about  C# but could this be from line 62 of Plugin.cs being changed from 
`this.Common = new XivCommonBase();` to `this.Common = new XivCommonBase(this.Interface);`?

**Comment by Athavar** [comment]
The change that has broken it was the renaming of the type `PeepingTomPlugin` to `Plugin`.
This should be fixed with version `2.1.0.0`
