### ISSUE TITLE
Craft queue rotation with Reflect doesn't work

### ISSUE THREAD

**Issue by colgeee** [Athavar/Athavar.FFXIV.Plugin#5]

**Comment by Athavar** [comment]
Can you please describe what exactly is not working with `Reflect`?

**Comment by colgeee** [comment]
it shows up in the rotation correctly, but would actually be skipped, resulting Reflect never been used.

**Comment by Athavar** [comment]
Ah, i have fix this with d64b230dcc0c00a019590769d8dc4ce488250c85 .
I will make a new build.
