### ISSUE TITLE
Causes crashes on exit - Unusually long start up/exit time

### ISSUE THREAD

**Issue by charmdi** [Athavar/Athavar.FFXIV.Plugin#53]
Hello,

Upon briefly installing this plugin and enabling one feature (not the DPS meter function) via XIVLauncher, I noticed FFXIV began to crash upon exiting from the menu. Disabling this plugin temporarily solved the issue for a few test start-ups/exits, however, unusually, all custom repo plugins began causing crashes upon exit. The only way to resolve this issue was to disable all custom repo plugins, which is not an issue I've encountered before.

Additionally, even when FFXIV was not crashing, upon legally selecting "exit the game" from the in-game menu, the game would stay paused on a black screen and then take take an unusually long time to terminate the program (20+ seconds, as opposed to the usual <5 seconds). It would also display the same issue upon starting up FFXIV.

Additionally, XIVLauncher informed me ACT had been installed on my computer (I have never installed ACT before, nor used a plugin that includes ACT or ACT-like functions; Atharvar is the first plugin I've touched that has included it). While this did not initially concern me, since the DPS meter function is a feature included with the Athavar toolbox, it did confuse me when I had fully removed the repo from XIVLauncher - and yet, XIVLauncher persisted in informing me ACT had been installed in my computer.

Uninstalling XIVLauncher and reinstalling it did not resolve these issues. I have also factory reset my laptop several times, including via the manufacturer clean slate factory reset, with guidance from the manufacturer. Custom repos continued to crash the game, even without Athavar installed. There is no pattern as to which custom repos have been affected. More directly linked to Athavar, I continue to receive notice that ACT has been installed in my system - even this many full factory resets later. Most puzzling is the persistence of ACT in my system - I've tried installing VoidEverything's search and could not find anything related to ACT on my system, and yet my system is still alerting me that it exists on it.

It appears there is some residual injection from the Athavar plugin that is persisting within the system itself, which is worrying. These issues have persisted across factory resets, so it appears the plugin has affected the system in an exceptionally fundamental way.

I would simply like to cleanly remove traces of Athavar from my system. If the developer could provide advice in this regard, I would appreciate it.

**Comment by Athavar** [comment]
First of all the plugin is using a different approach than ACT. ACT is using winpcap or if enabled Deucalion (memory injection) to get network packages with the combat data.
My plugin is using the NetworkMessage event from the dalamud GameNetwork service to access the game network packages.
The only file system location that are accessed is the configuration directory _%AppData%\XIVLauncher/pluginConfigs/Athavar.FFXIV.Plugin/_.

If you want to delete the plugin follow the steps on https://goatcorp.github.io/faq/dalamud_troubleshooting#q-how-do-i-manually-delete-plugins

**Comment by Athavar** [comment]
And if you want to know why the startup is slow you can use the "Profiler" in the dev menu(you can open it by clicking a small invisible box top left in the game title screen)

**Comment by Athavar** [comment]
From what I have seen in the "XIVLauncher & Dalamud" discord the popup about ACT is a bug. This popup is broken and will be removed in the next version of the launcher: https://github.com/goatcorp/FFXIVQuickLauncher/commit/979ad888da34c8f8f032fd37ef00aa56ee28f836.
To verify that this plugin is causing the long startup please use the **Profiler**.
And without log I can't verify and find the cause of the crash.
