### ISSUE TITLE
Trained perfection ability not working

### ISSUE THREAD

**Issue by Dididada1212** [Athavar/Athavar.FFXIV.Plugin#56]
When creating a rotation that contains the "Trained Perfection" ability and try to use that rotation in a queue, the plugin gives an error saying I ran out of durability.
For some reason Trained perfection consumes durability and it doesnt remove the durability cost from the next ability in the rotation.

**Comment by Athavar** [comment]
Thanks for reporting this. The action ids from 'Daring Touch' where wrong(copy/past error). Fixed with v2.2.1.7. Please recheck the saved rotation.

**Comment by Dididada1212** [comment]
Yup, after the update it changed to Daring Touch, had to change it to Trained Perfection and now its working.
Thank you!
