### ISSUE TITLE
Can't change Error Chat Channel

### ISSUE THREAD

**Issue by X3llus** [Athavar/Athavar.FFXIV.Plugin#58]
In the settings menu under chat, when I try to change the "Error chat channel" it seems to change the "Normal chat channel" instead, changing the normal chat channel seems to work work normally though.

**Comment by Athavar** [comment]
Fixed with [v2.2.1.10](https://github.com/Athavar/Athavar.FFXIV.Plugin/releases/tag/v2.2.1.10)
