### ISSUE TITLE
Grade 2 gemdraughts doesn't load the steps for any rotation

### ISSUE THREAD

**Issue by Dididada1212** [Athavar/Athavar.FFXIV.Plugin#59]
I am trying to add Grade 2 gemdraught to a queue, and no matter what rotation I choose it doesnt load any steps or show me what progress/quality I will get, which prevents adding it to a crafting queue.

No issue detected by other 7.05 crafts and only the gemdraughts.

**Comment by Athavar** [comment]
I can't reproduce it with my rotation and stats. Even if I select a rotation that is failing the craft the steps/reached progress is displayed.
Can you provide the crafting stats and rotation?

**Comment by Dididada1212** [comment]
Un-equipping an item then save my set and refresh my stats resolved the issue, I re-equipped the item and saved again and the issue didn't replicate.
Not sure what caused it in the first place but hopefully it wont replicate again in the future.
