### ISSUE TITLE
AFK timer may trigger during crafting

### ISSUE THREAD

**Issue by zeroeightysix** [Athavar/Athavar.FFXIV.Plugin#60]
It's possible for the player to send the AFK status while a craft job is running, which probably looks suspicious to any onlookers and to the server.

**Comment by Athavar** [comment]
Should be fixed with [v2.2.1.11](https://github.com/Athavar/Athavar.FFXIV.Plugin/releases/tag/v2.2.1.1).
I have added code that is triggering a key press at the start of a craft, if the last game input was 60 seconds ago.
