### ISSUE TITLE
ER: [CraftQueue] Materia extract & [Dps] Add Crit/DHit

### ISSUE THREAD

**Issue by ResFox** [Athavar/Athavar.FFXIV.Plugin#7]
Hey, nice work on the plugin! 
Is there a possibility to add the %crit %dhit and max hit in the parser? Would be really nice!
Also for the crafter, any chance to get the auto "extract materia" and the "repair" ?

**Comment by Athavar** [comment]
`craftqueue` has already a repair-feature.
I implemented the rest in a branch(commit 4101ddc0868f80a3a5df8b04ccb46bba725c8772 and 3ceb23948ed9fd5ed3e5d2ce256e7c7ae7b91af2), but I need to test first if it works correctly.

**Comment by Athavar** [comment]
As a note: 4101ddc0868f80a3a5df8b04ccb46bba725c8772 and 3ceb23948ed9fd5ed3e5d2ce256e7c7ae7b91af2 where merged with #8 and are included in release v2.0.17(https://github.com/Athavar/Athavar.FFXIV.Plugin/releases/tag/v2.0.17)

**Comment by Athavar** [comment]
With #14 the interaction with MaterializeDialog Addon is also now fixed.
